spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/sudol_tree
  jpa:
    hibernate:
      ddl-auto: create
